# Enable or disable world regeneration
default-regen: true

# The default regen speed in ticks
default-regen-speed: 2

# The default regen delay in ticks
default-regen-delay: 10

# Default block types that are replaced on heal
default-replace-blocks:
  "minecraft:deepslate_bricks": 'minecraft:cracked_deepslate_bricks'
  "minecraft:deepslate_tiles": 'minecraft:cracked_deepslate_tiles'
  "minecraft:nether_bricks": 'minecraft:cracked_nether_bricks'
  "minecraft:polished_blackstone_bricks": 'minecraft:cracked_polished_blackstone_bricks'
  "minecraft:stone_bricks": 'minecraft:cracked_stone_bricks'
